// Database types for TheGlocal project
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          username: string;
          email: string;
          first_name: string;
          last_name: string;
          bio?: string;
          avatar_url?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          date_of_birth?: string;
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say';
          created_at: string;
          updated_at: string;
          is_anonymous: boolean;
          privacy_level: 'public' | 'private' | 'anonymous';
          anonymous_handle?: string;
          anonymous_display_name?: string;
          real_name_visibility: boolean;
          location_sharing: boolean;
          precise_location: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          username: string;
          email: string;
          first_name: string;
          last_name: string;
          bio?: string;
          avatar_url?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          date_of_birth?: string;
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say';
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          privacy_level?: 'public' | 'private' | 'anonymous';
          anonymous_handle?: string;
          anonymous_display_name?: string;
          real_name_visibility?: boolean;
          location_sharing?: boolean;
          precise_location?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          username?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          bio?: string;
          avatar_url?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          date_of_birth?: string;
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say';
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          privacy_level?: 'public' | 'private' | 'anonymous';
          anonymous_handle?: string;
          anonymous_display_name?: string;
          real_name_visibility?: boolean;
          location_sharing?: boolean;
          precise_location?: boolean;
        };
      };
      communities: {
        Row: {
          id: string;
          name: string;
          description?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          created_by: string;
          created_at: string;
          updated_at: string;
          is_public: boolean;
          member_count: number;
          category?: string;
          tags?: string[];
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          is_public?: boolean;
          member_count?: number;
          category?: string;
          tags?: string[];
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          is_public?: boolean;
          member_count?: number;
          category?: string;
          tags?: string[];
        };
      };
      posts: {
        Row: {
          id: string;
          title: string;
          content: string;
          author_id: string;
          community_id?: string;
          category?: string;
          tags?: string[];
          image_url?: string;
          created_at: string;
          updated_at: string;
          is_anonymous: boolean;
          anonymous_handle?: string;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          author_id: string;
          community_id?: string;
          category?: string;
          tags?: string[];
          image_url?: string;
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          anonymous_handle?: string;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          author_id?: string;
          community_id?: string;
          category?: string;
          tags?: string[];
          image_url?: string;
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          anonymous_handle?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          content: string;
          author_id: string;
          post_id: string;
          parent_comment_id?: string;
          created_at: string;
          updated_at: string;
          is_anonymous: boolean;
          anonymous_handle?: string;
        };
        Insert: {
          id?: string;
          content: string;
          author_id: string;
          post_id: string;
          parent_comment_id?: string;
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          anonymous_handle?: string;
        };
        Update: {
          id?: string;
          content?: string;
          author_id?: string;
          post_id?: string;
          parent_comment_id?: string;
          created_at?: string;
          updated_at?: string;
          is_anonymous?: boolean;
          anonymous_handle?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          description: string;
          event_date: string;
          event_time: string;
          location_name: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          price?: number;
          user_id: string;
          created_at: string;
          updated_at: string;
          category?: string;
          tags?: string[];
          featured: boolean;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          event_date: string;
          event_time: string;
          location_name: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          price?: number;
          user_id: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          event_date?: string;
          event_time?: string;
          location_name?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          price?: number;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
        };
      };
      virtual_protests: {
        Row: {
          id: string;
          title: string;
          description: string;
          protest_date: string;
          protest_time: string;
          location_name: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          organizer_id: string;
          created_at: string;
          updated_at: string;
          category?: string;
          tags?: string[];
          featured: boolean;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          protest_date: string;
          protest_time: string;
          location_name: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          organizer_id: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          protest_date?: string;
          protest_time?: string;
          location_name?: string;
          location_city?: string;
          location_state?: string;
          location_country?: string;
          latitude?: number;
          longitude?: number;
          image_url?: string;
          max_attendees?: number;
          organizer_id?: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
        };
      };
      news_articles: {
        Row: {
          id: string;
          title: string;
          content: string;
          summary?: string;
          author: string;
          source_url?: string;
          image_url?: string;
          created_at: string;
          updated_at: string;
          category?: string;
          tags?: string[];
          featured: boolean;
          published: boolean;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          summary?: string;
          author: string;
          source_url?: string;
          image_url?: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
          published?: boolean;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          summary?: string;
          author?: string;
          source_url?: string;
          image_url?: string;
          created_at?: string;
          updated_at?: string;
          category?: string;
          tags?: string[];
          featured?: boolean;
          published?: boolean;
        };
      };
      interests: {
        Row: {
          id: string;
          name: string;
          description?: string;
          category?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      privacy_settings: {
        Row: {
          id: string;
          user_id: string;
          profile_visibility: 'public' | 'private' | 'anonymous';
          show_email: boolean;
          show_phone: boolean;
          show_location: boolean;
          anonymous_mode: boolean;
          anonymous_posts: boolean;
          anonymous_comments: boolean;
          anonymous_votes: boolean;
          location_sharing: boolean;
          precise_location: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          profile_visibility?: 'public' | 'private' | 'anonymous';
          show_email?: boolean;
          show_phone?: boolean;
          show_location?: boolean;
          anonymous_mode?: boolean;
          anonymous_posts?: boolean;
          anonymous_comments?: boolean;
          anonymous_votes?: boolean;
          location_sharing?: boolean;
          precise_location?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          profile_visibility?: 'public' | 'private' | 'anonymous';
          show_email?: boolean;
          show_phone?: boolean;
          show_location?: boolean;
          anonymous_mode?: boolean;
          anonymous_posts?: boolean;
          anonymous_comments?: boolean;
          anonymous_votes?: boolean;
          location_sharing?: boolean;
          precise_location?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
