name: Simple Deployment to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate required secrets
      run: |
        echo "🔍 Checking required GitHub Secrets..."
        if [ -z "${{ secrets.VITE_SUPABASE_URL }}" ]; then
          echo "❌ VITE_SUPABASE_URL secret is not set"
          echo "Please add VITE_SUPABASE_URL to your repository secrets"
          echo "Go to: Settings → Secrets and variables → Actions"
          exit 1
        fi
        if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
          echo "❌ VITE_SUPABASE_ANON_KEY secret is not set"
          echo "Please add VITE_SUPABASE_ANON_KEY to your repository secrets"
          echo "Go to: Settings → Secrets and variables → Actions"
          exit 1
        fi
        echo "✅ Required secrets are configured"
        echo "📋 Supabase URL: ${{ secrets.VITE_SUPABASE_URL }}"
        echo "🔑 Anon Key: ${VITE_SUPABASE_ANON_KEY:0:20}..."
    
    - name: Build project
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
        VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY }}
        VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
        VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
        CI: true
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🌐 Your site is now available at:"
        echo "   https://ydvvpn197-netizen.github.io/projectglocal/"
        echo ""
        echo "Next steps:"
        echo "1. Test your deployed site"
        echo "2. Check all features are working"
        echo "3. Add optional secrets for enhanced features"
