name: Complete Deployment to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests (for emergency deployments)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  BUILD_DIR: 'dist'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci

      - name: Validate environment variables
        run: |
          if [ -z "${{ secrets.VITE_SUPABASE_URL }}" ]; then
            echo "⚠️ Missing VITE_SUPABASE_URL secret - using default for build"
          else
            echo "✅ VITE_SUPABASE_URL found"
          fi
          if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            echo "⚠️ Missing VITE_SUPABASE_ANON_KEY secret - using default for build"
          else
            echo "✅ VITE_SUPABASE_ANON_KEY found"
          fi
          echo "✅ Environment validation complete"

      - run: npm run type-check
      - run: npm run lint

      - name: Run tests
        if: ${{ inputs.skip_tests != true }}
        run: npm run test:run
        env:
          CI: true

      - name: Test Supabase connection
        run: npm run test:supabase
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://placeholder.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'placeholder_key' }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: validate
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - name: Build project
        run: |
          echo "🔨 Starting build process..."
          npm run build
          echo "✅ Build completed successfully"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://placeholder.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'placeholder_key' }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY || '' }}
          VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY || '' }}
          VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY || '' }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY || '' }}
          CI: true
      - name: Validate build output
        run: |
          if [ ! -d "${{ env.BUILD_DIR }}" ]; then echo "❌ Build dir not found"; exit 1; fi
          if [ ! -f "${{ env.BUILD_DIR }}/index.html" ]; then echo "❌ index.html missing"; exit 1; fi
          echo "✅ Build output validated"
          ls -la ${{ env.BUILD_DIR }}
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}
      - id: deployment
        uses: actions/deploy-pages@v4

  verify:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: always()
    steps:
      - run: sleep 30
      - run: |
          if [ "${{ needs.build-and-deploy.result }}" = "success" ]; then
            echo "✅ Deployment completed: https://ydvvpn197-netizen.github.io/projectglocal/"
          else
            echo "❌ Deployment failed"; exit 1;
          fi
      - run: |
          SITE_URL="https://ydvvpn197-netizen.github.io/projectglocal/"
          if curl -s -o /dev/null -w "%{http_code}" "$SITE_URL" | grep -q "200"; then
            echo "✅ Site is accessible"
          else
            echo "⚠️ Site may not be fully deployed yet"
          fi

  notify:
    runs-on: ubuntu-latest
    needs: [validate, build-and-deploy, verify]
    if: always()
    steps:
      - run: |
          echo "📊 Deployment Summary"
          echo "Validate: ${{ needs.validate.result }}"
          echo "Build & Deploy: ${{ needs.build-and-deploy.result }}"
          echo "Verify: ${{ needs.verify.result }}"
